language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt-cli
env:
  global:
    secure: MqRjvijLuuKDyeV6acMgVPRem0GDAkAwWm2GhcUI0wLxx7HBHK+ZHMdD6YMZhsqGn1yXPJm6/qeBF4WabwK7d/XV6VG2wNM2f2qvp+ddQGDpS1gp8on1/+c10ndg970BG6MF45hAeoki8vyNcpjmP1tQ8itSyaXQ52MPjcPPoUY=
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: NMAtsfhxN8w+4KUpeebx8JgCa2r0/mztux7W30tgV8TBe81xWmq6S5KxLSCEm8AkZGM897rK4rhumuDut6f8LnSddkdXoLoPaO/NKQiX/XCgkv8j2sNGnweew6q8m4nJwQvjbs6jVU3qCHLxQ6DqflcjVPGVpDm8rto6au7do2Q=
  on:
    tags: true
    repo: noflo/noflo-github
